### PR TITLE
Translate Ruby 2.4.0-rc1 (es)

### PR DESCRIPTION
**Pull request by FerPerales**

### CODE REVIEW

**Comment by stomar** [comment]
Thanks. How about the final 2.4.0 post? Seems more important than rc...

cc @dabit

**Comment by FerPerales** [comment]
@stomar Tackle that one on a different PR: https://github.com/ruby/www.ruby-lang.org/pull/1547 cc @dabit

**Comment by stomar** [comment]
Yep, I've noticed too late.

**Comment by stomar** [comment]
Small fixes in 14d0da19e3982a3e6bfd2a4e97c3c85f892d521f.

Please wrap at max. 80 characters and keep same paragraphs as `en` version.

**Pull request merged**
