### PR TITLE
improve the libraries documentation [en]

### PR DESCRIPTION
**Pull request by colby-swandale**
This PR improves some of the wording and flow in the `libraries` page, i felt that some of the wording felt a bit awkward and incomplete in some areas.

Let me know what you think.

Thanks!

### CODE REVIEW

**Comment by hsbt** [comment]
Can anyone review this? I couldn't review English sentences because I'm not a native speaker.

**Comment by stomar** [comment]
Didn't have time in the last weeks for open source. I'll look into this these days.

**Comment by JuanitoFatas** [comment]
@zzak Want to take a look?

**Comment by stomar** [comment]
@colby-swandale Thanks for your contribution, and sorry for the delay.

**Pull request merged**
