### PR TITLE
Remove abuse enabling language

### PR DESCRIPTION
**Pull request by jacobherrington**
My rationale for these changes are documented on Twitter:
https://twitter.com/JakeHerrington/status/1443286841533374469

### CODE REVIEW

**Review by ibiwan-intuit — APPROVED** [review]

**Comment by hmdne** [comment]
I suggest we also remove this point from the conduct guidelines:

```
  * Participants will be tolerant of opposing views.
```

Some people may have views that when expressed, may be harmful to the interest of particular groups of people like big corporations. This has to be taken into account.

**Review by olivierlacan — APPROVED** [review]
I wholeheartedly approve this PR, for a host of reasons anyone willing to [educate](https://thoughtbot.com/blog/beyond-best-intentions) themselves could learn without me having to repeat them.

Intentions are not magical shields against criticism. Our community deserves our having higher standards for discourse and standing up to casual misogyny in the form of repeated tasteless so-called jokes by anyone, ever.

**Comment by jacobherrington** [comment]
@hmdne I think that's a good point, but I'd like to be as explicit as possible in this PR; I watched a group of people use these specific phrases to justify making sexist remarks over a communication channel that falls under these guidelines. I really would like to see them removed, so I don't want to push beyond that goal.

However, I think it'd be a good idea for you to open another PR and suggest your change! I'd be in support of finding a better way to communicate the spirit of tolerance and mutual respect without implying that anyone is obligated to tolerate harmful behavior.

**Comment by hmdne** [comment]
@jacobherrington I disagree. I view this PR is to fix the holes that people with other worldviews may use. Why fix one hole while leaving another wide open?

And while we are at it, maybe also we should correct this rule:

```
  * Behaviour which can be reasonably considered harassment will not be tolerated.
```

To become something like (what do other posters think? Can we make it even stricter?):

```
  * Behaviour which can be considered harassment will not be tolerated.
```

The law should always protect the victim, not the perpetrator. This is so that a harasser won't be able to use a meritocracy argument, which as we all know, is dehumanizing:

https://modelviewculture.com/pieces/the-dehumanizing-myth-of-the-meritocracy

**Comment by jacobherrington** [comment]
@hmdne I don't disagree with your points, but I think these changes are distinct and for the sake of the Ruby maintainers, we should be specific in each PR.

I really do think having a broader discussion is important and your points should be part of that discussion.

Opening an issue on this repository could be a good place to start; re-writing the guidelines document will require buy-in from the larger community and the maintainers.

I'm hoping by keeping the suggestion small and pointing to a real world example of this language enabling harm, it won't be so hard to get the ball rolling.

**Comment by hmdne** [comment]
I understand @jacobherrington. I will participate in this discussion. It will be very important to hear other feedback before we come up with a coherent PR.

Let me just quote the post, which started all this:

> Hello,
> 
> Another example - perhaps somebody could fix that (many errors have that
> source!)
> 
> Date.today
> 
> Date.today +1    # no error, but wrong result!
> 
> # Maybe this has been written for women, having calculated their age ;)

I am shocked that some people defended this person, as it is clearly against the universally accepted corporate values. There should be absolutely no tolerance for making jokes mentioning the protected classes.

**Review by JuanitoFatas — APPROVED** [review]
👍🏼 👍🏼 👍🏼

**Comment by hmdne** [comment]
Encouraged by the quick success of this PR, I made #2691 with another small change. One step at a time at fixing the world :)

**Comment by hsbt** [comment]
@JuanitoFatas WAIT. `en/conduct/index.md` is created by @matz originally. We should approve from him before merging this.

**Comment by Try2Code** [comment]
> Encouraged by the quick success of this PR, I made #2691 with another small change. One step at a time at fixing the world :)

sry, but this is getting ridiculous. all this wording about good intentions  - so with this conduct we are all good ppl talking no trash, always the right way (yes, sir!). 

As a consequence, there will be 
- no more space for any kind of humor (cause someone could feel shocked)
- no more general criticism (cause some ppl might feel too offended) unless we use the perfect working for that (btw: do we have a dictionary already for expressing criticism in an correct way. I would like to have one - just to be on the save side)
-  but hang on: what if some ppl still feel offended even IF we use the right words? Do they loose the right to feel offended in that case?

zero tolerance means that we end up in our happy-pink-pony-farm-world and I don;t think this is a healthy development. I agree with the _try-to-be-nice_ approach to 100%, but it's only an approach. It's nothing we can enforce in my opinion. I think discussions should be open and free unless people get insulting like on a personal level. this is totally off-topic in should be done in a private chat. We need responsible ppl who moderate discussions so that everyone feels save, pointing to rules does not do the trick from my experience.

**Comment by hmdne** [comment]
>but hang on: what if some ppl still feel offended even IF we use the right words? Do they loose the right to feel offended in that case?
@Try2Code if they are not a protected class, they will lose that right, yes. That's California Core Corporate Policies in work. And we enacted them.

**Comment by Try2Code** [comment]
ok, so as long as u belong to a protected class you are allowed to feel offended. who are these classes?

**Comment by hmdne** [comment]
@Try2Code That's common sense. We all know who are protected classes. For instance, members of board of directors of the big corporations are a protected class.

**Comment by peterc** [comment]
Since California has been mentioned, I'm guessing these: https://www.senate.ca.gov/content/protected-classes

Everyone belongs to protected classes depending on context. It's not about some people being protected and some not. Everyone has a sexual orientation, marital status, race, etc. and harassment on such characteristics is verboten. (Although it was before too - the change in #2691 actually seems to _reduce_ the scope of what is considered harassment to me as it was universal before?)

**Comment by hmdne** [comment]
@peterc I disagree. According to the latest guidelines, there is no such thing as a "reverse racism" or "reverse sexism".

**Comment by Try2Code** [comment]
hang on (again): we use the term _protected class_ and do not know what is mean? semantics?

**Comment by hmdne** [comment]
@Try2Code Everyone knows what a protected class means.

**Comment by Try2Code** [comment]
sorry - this is a very weak explanation. esp. if you want to judge peoples behavior on it. THIS opens the door for many possibly fruitless discussions about _what people think_ should be a protected class.

Ether you have a definition for it or your don't. but in that case the term should simply not be used. 
Isn't it just to central for the whole point of having a conduct to do without a clear definition?

**Comment by jacobherrington** [comment]
> @JuanitoFatas WAIT. `en/conduct/index.md` is created by @matz originally. We should get approval from him before merging this.

I would very much like @matz thoughts on this change. If he feels these guidelines shouldn't change it should be reverted.

However, I will definitely continue to advocate that these two guidelines change, even if it is decided that the commit is reverted.

There are likely more places the Ruby guidelines should be revisited, but these two lines were specifically used to justify making casual sexist jokes on the ruby-talk mailing list; they should be changed if Ruby, as a project, opposes that sort of behavior (I would think this so).

**Comment by hmdne** [comment]
@Try2Code We don't have to define a "computer". We all know what protected classes are and if you don't, you will need to educate.

@jacobherrington Matz already approved of those changes.

**Comment by Try2Code** [comment]
@hmdne you obviously do not want to answer my question. There IS a definition of a computer and a definition of a car. but here we do not touch the physical world, but social interaction between humans. 

And all you can say is: guy, you should know what I am talking about, but I won't tell you. please educate yourself. 

Then please, educate me! Where is the definition? I was just asking for that education in my post before, but you do not seem to willing to provide it. why? did I write something wrong?

**Comment by hsbt** [comment]
Unfortunately, I also didn't know what means "protected classes" until this discussion. In Japan, We don't use "protected classes" terminology, We use "Race, Color, Religion, Gender, ... etc" explicitly.

I understand @Try2Code situation.  I'm asking this to @matz in next week.

**Pull request merged**
