### PR TITLE
Translate recent posts to de

### PR DESCRIPTION
**Pull request by Quintus**
Most recent posts translated to German. Filing as a PR because quite a number of posts at once so this may ease checking them for errors.

Valete,
Quintus

### CODE REVIEW

**Comment by stomar** [comment]
@Quintus Some small fixes.

**Comment by stomar** [comment]
@Quintus Let's merge?

**Comment by Quintus** [comment]
Marcus Stollsteimer <notifications@github.com> writes:

> @Quintus Let's merge?

I’m sorry, yes. I was very busy in the last weeks (university
exams). Shall I merge it or do you want to do it?

Vale,
Quintus

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by stomar** [comment]
doesn't matter :)

**Comment by stomar** [comment]
Thanks as always for the translations, I was pretty busy lately, too.

Und viel Erfolg bei allen eventuell noch ausstehenden Prüfungen!

**Comment by Quintus** [comment]
Marcus Stollsteimer <notifications@github.com> writes:

> Thanks as always for the translations, I was pretty busy lately, too.

That’s life :-)

> Und viel Erfolg bei allen eventuell noch ausstehenden Prüfungen!

Danke :-)

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Pull request merged**
