### PR TITLE
Add all missing news (it)

### PR DESCRIPTION
**Pull request by Arkham**
@alepore please review :rainbow:

### CODE REVIEW

**Comment by kennyadsl** [comment]
@Arkham thanks!

**Comment by stomar** [comment]
@Arkham Thanks for all the translations.

For future PRs please try to wrap lines at 80 characters (excepting links).
Also, keeping links on a separate line, like it's (usually) done in the original posts, makes a `diff` with the en version much easier to read.

**Comment by alepore** [comment]
:heart_eyes: yeahh

**Comment by Arkham** [comment]
@stomar thanks for the comments, will do in the next PRs :)

**Pull request merged**
