### PR TITLE
Fix example code in 3.0.0-rc1 post

### PR DESCRIPTION
**Pull request by stomar**
It should be `Ractor.receive` instead of `Ractor.recv`.

### CODE REVIEW

**Comment by stomar** [comment]
At least it seems like it, according to the docs and the code in the `ja` version. I couldn't test the code yet.

**Comment by ismailarilik** [comment]
I have just merged the Turkish translation. Do I have a chance to change the code for this translation in this PR?

**Comment by stomar** [comment]
I can fix it as soon as the change is confirmed.

**Comment by stomar** [comment]
@nurse

A side note: a diff shows discrepancies between `en` and `ja` version, i.e. `Fiber#scheduler` <-> `Thread#scheduler`.

**Comment by nurse** [comment]
> @nurse
> 
> A side note: a diff shows discrepancies between `en` and `ja` version, i.e. `Fiber#scheduler` <-> `Thread#scheduler`.

Thanks! merged that

**Review by JuanitoFatas — APPROVED** [review]

**Pull request merged**
