### PR TITLE
Translate all August 2015 news (id)

### PR DESCRIPTION
**Pull request by meisyal**
As titled.
Please, review my translation @gozali!
Thank you so much.

cc: @stomar

### CODE REVIEW

**Comment by stomar** [comment]
@meisyal I'm ok with merging these PRs without language review, unless you would prefer it.

LGTM?

**Comment by gozali** [comment]
Reviewed 

+1 thanks @meisyal 

Sorry guys, been busy with my newborn among other things

**Comment by stomar** [comment]
@gozali  Congrats! :fireworks: 

@meisyal Thanks for the effort!

**Comment by meisyal** [comment]
No problem, @gozali. By the way, congratulation!

You're welcome, @stomar.

**Pull request merged**
