### PR TITLE
Use dizer_ola instead of diz_ola for Anfitriao class (pt)

### PR DESCRIPTION
**Pull request by spk**
see #1019

### CODE REVIEW

**Comment by stomar** [comment]
Methods are about sending messages, therefore the imperative should be used, IMO. (Which would be `diz`, if I am not mistaken.)

And please note the affected languate in commit messages, like in e.g. `Change method name in example (pt)`.

**Comment by chikamichi** [comment]
@spk didn't know you speak Portugese.

**Comment by spk** [comment]
@chikamichi I don't I thought it was that.
@stomar updated.

**Comment by chikamichi** [comment]
Pas compris. Tu parles pas portugais mais tu fais des commits en portugais ? :monkey_face:

**Comment by spk** [comment]
@chikamichi Tu as compris :exclamation: :see_no_evil:

**Comment by JuanitoFatas** [comment]
@stomar merge this?

**Pull request merged**
