### PR TITLE
Switch to Ruby 2.3.1

### PR DESCRIPTION
**Pull request by stomar**

### CODE REVIEW

**Comment by stomar** [comment]
Travis CI build is ok.

**Comment by stomar** [comment]
@hsbt CI build status is no longer displayed in the PR's, and also I got the impression that automatic deploys to staging do not work currently. Has the config been changed somehow?

**Comment by hsbt** [comment]
@stomar fmm, I didn't change github and heroku configuration. I'm going to investigate it.

**Comment by hsbt** [comment]
@stomar I fixed at https://github.com/ruby/www.ruby-lang.org/commit/c11b8080b6f8e07148861fbeb68303a27f6ec4b0 . Sorry to contains my dirty commits.

It caused with heroku configuration of automatic deploys. If you have another concerns, Please ping me.

**Pull request merged**
