### PR TITLE
Translate Ruby 2.6.5 Release News (id)

### PR DESCRIPTION
**Pull request by kuntoaji**

### CODE REVIEW

**Comment by meisyal** [comment]
Hi @kuntoaji, I left some comments on your translation. Could you check?

**Comment by kuntoaji** [comment]
> Hi @kuntoaji, I left some comments on your translation. Could you check?

sorry, where is your comment?

**Comment by meisyal** [comment]
> > Hi @kuntoaji, I left some comments on your translation. Could you check?
> 
> sorry, where is your comment?

Could you check again?

**Comment by kuntoaji** [comment]
@meisyal all done

**Comment by meisyal** [comment]
Thank you so much @kuntoaji. Merged.

**Pull request merged**
