### PR TITLE
to-ruby-from-python functional programming

### PR DESCRIPTION
**Pull request by StephenLujan**
Added one bullet point of similarities and two of differences, regarding functional programming, in to-ruby-from-python/index.md

### CODE REVIEW

**Comment by stomar** [comment]
Coudl you squash commits?

**Comment by StephenLujan** [comment]
Commits are now squashed.

**Comment by nono** [comment]
Thanks @StephenLujan

**Comment by stomar** [comment]
@nono `en` content changes should be approved by editorial team.

**Comment by nono** [comment]
@stomar sorry, I thought it was OK as it is only minor additions to an already existing page.

**Comment by stomar** [comment]
you can confirm the statements about Python?

**Comment by nono** [comment]
Yes, I do.

**Comment by stomar** [comment]
Ok, thanks!

**Pull request merged**
