### PR TITLE
Add Atom text editor to documentation.

### PR DESCRIPTION
**Pull request by gfvcastro**

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
:+1:

**Comment by chikamichi** [comment]
Good idea. Merging?

**Comment by stomar** [comment]
Thanks! (Merged manually with e42de62c2a3ad76c5551959397dc99e0d6dd29d4.)

(Please indicate lang in commit message and use short branch names.)

**Comment by gfvcastro** [comment]
@stomar: I will remember. Thanks. :+1:

**Pull request closed without merging**
