### PR TITLE
Use Lanyon instead of rack-jekyll

### PR DESCRIPTION
**Pull request by stomar**
@hsbt 

I switched from rack-jekyll to the (new) lanyon gem.

rack-jekyll is essentially unmaintained and until a couple of weeks ago was a real mess: buggy, no tests at all, unused garbage code... After providing lots of tests and essentially nearly rewriting the whole thing, I decided to start fresh with a new gem, "Lanyon". It should work work just as good, and drops some functionality that we do not need (namely: no auto regeneration).

Note: lanyon 0.2.0 is the first gem release; versions 0.1.x belong to an unrelated yanked gem.

### CODE REVIEW

**Comment by stomar** [comment]
After CI checks passed and staging looked fine it's now in production.

Please report any problems.

**Comment by hsbt** [comment]
@stomar Great. I have bit of worry for maintenance status of rack-jekyll. I'm ok to replace with  https://github.com/stomar/lanyon/ .

**Comment by stomar** [comment]
> I have bit of worry for maintenance status of rack-jekyll

Yep, me too. It was really an effort to get gem updates pushed to RubyGems.org.

**Comment by JuanitoFatas** [comment]
Nice work! :clap:

**Pull request merged**
