### PR TITLE
Update outdated download page (id)

### PR DESCRIPTION
**Pull request by meisyal**
I updated download page (Bahasa Indonesia). The outdated warning at the top of page is removed.
Please, review the translation @gozali!
Thank you.

Fix #1316.
cc: @stomar

### CODE REVIEW

**Comment by stomar** [comment]
Thank you! Merged manually with d6f15f8cd789b11e21aeb2a8f785ec0f322e300d (and 3918e0e97f17186d00e4d99d72a82f4f7967449a).

Still open: The paragraph on the documentation page that links to the installation page.

**Comment by meisyal** [comment]
You're welcome.
Which part of the paragraph on the documentation page that links to the installation page?

**Comment by stomar** [comment]
Sorry, I meant the complete "Installing Ruby" section on the documentation page.

**Comment by meisyal** [comment]
Oh, I see. I will work on it @stomar.
Thank you.

**Pull request closed without merging**
