### PR TITLE
Fix translation in index (tr)

### PR DESCRIPTION
**Pull request by msms6174**
An item has been translated to the Turkish language.

### CODE REVIEW

**Comment by stomar** [comment]
Thanks,

but please use a single commit and PR for #1119 and #1118, and provide a meaningful commit message (nearly all files are named index.md!), like e.g. `Fix translation of to-ruby-from-python (tr)`; more is not necessary.

**Comment by stomar** [comment]
Merged manually with b70aa0f14efca412966ce3c8ca50f26d92985743.

**Comment by stomar** [comment]
@msms6174 Thanks again for your contribution.

I merged because these (small) changes seemed ok, but note that right now nobody here can proofread Turkish content, the `tr` part of the site is unmaintained.

**Comment by msms6174** [comment]
You are right. It would be better a Turkish developer takes place in the
contributors. But these changes are OK, I carefully translated content to
Turkish. Trust me. =)

2015-06-13 22:01 GMT+03:00 Marcus Stollsteimer <notifications@github.com>:

> @msms6174 <https://github.com/msms6174> Thanks again for your
> contribution.
>
> I merged because these (small) changes seemed ok, but note that right now
> nobody here can proofread Turkish content, the tr part of the site is
> unmaintained.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby/www.ruby-lang.org/pull/1119#issuecomment-111740678>
> .
>



-- 
İsmail Arılık

**Comment by stomar** [comment]
I did, or I wouldn't have merged :smile:

**Pull request closed without merging**
