### PR TITLE
Add link to ruby issues to all translated articles

### PR DESCRIPTION
**Pull request by riseshia**
apply #1489 to all translated articles

@ruby/www-ruby-lang-org-i18n-ko could someone confirm this? XD

### CODE REVIEW

**Comment by marocchino** [comment]
Can you apply it to other langs, please? 😄 

- de/news/_posts/2016-09-08-ruby-2-4-0-preview2-released.md
- es/news/_posts/2016-09-08-ruby-2-4-0-preview2-released.md
- it/news/_posts/2016-09-08-ruby-2-4-0-preview2-released.md
- zh_tw/news/_posts/2016-09-08-ruby-2-4-0-preview2-released.md
- ja/news/_posts/2016-11-09-ruby-2-4-0-preview3-released.md

**Comment by riseshia** [comment]
@marocchino is it ok?

**Comment by marocchino** [comment]
Sure.

**Comment by riseshia** [comment]
👍 ok, I will apply this to all XD

**Comment by riseshia** [comment]
Done :)

**Pull request merged**
