### PR TITLE
Translate Ruby 2.4.0-rc1 released post (id)

### PR DESCRIPTION
**Pull request by meisyal**
@gozali please help to review this translation!
Let me know if there are typos or translation mistakes.

### CODE REVIEW

**Comment by gozali** [comment]
Translation looks good. don't forget to put a new line at the end of the file @meisyal. Thanks

**Comment by meisyal** [comment]
Thank you @gozali.
cc: @stomar

**Comment by stomar** [comment]
Thanks. There are slight differences to preview3 post (e.g. single letters), maybe typos?

**Comment by meisyal** [comment]
:+1:

Where is it?

**Pull request merged**
