### PR TITLE
Update French user groups page

### PR DESCRIPTION
**Pull request by cveneziani**
- Fix typos in How to create a Ruby user group

cc @nono :)

### CODE REVIEW

**Comment by nono** [comment]
Thanks @cveneziani !

**Comment by cveneziani** [comment]
Thanks for the review!
I'm sorry to ping you each time I submit a PR on Ruby website.

Is there a team of French speaking collaborators that I could ping next time?

**Comment by skade** [comment]
@cveneziani @ruby/www-ruby-lang-org-i18n-fr is the team handle.

**Comment by cveneziani** [comment]
Looks like it's not a public team. Will it work if I mention the team?

**Pull request merged**
