### PR TITLE
Use Ruby 2.4

### PR DESCRIPTION
**Pull request by stomar**
not yet sure when Heroku / Travis CI are ready for 2.4 ...

### CODE REVIEW

**Comment by stomar** [comment]
Travis CI can handle it obviously, and push to heroku also succeeded... merging.

**Comment by stomar** [comment]
@hsbt already in production.

**Comment by stomar** [comment]
Note to myself:

With the change to Ruby 2.4 there happened a slight change in the generated site (RSS feeds):

```
diff -r _site_5103179/en/feeds/news.rss _site_d5c5141/en/feeds/news.rss
297c297
<       <pubDate>Mon, 12 Dec 2016 09:00:00 +0000</pubDate>
---
>       <pubDate>Mon, 12 Dec 2016 18:00:00 +0900</pubDate>
643c643
<       <pubDate>Wed, 09 Nov 2016 09:00:00 +0000</pubDate>
---
>       <pubDate>Wed, 09 Nov 2016 18:00:00 +0900</pubDate>
857c857
<       <pubDate>Thu, 08 Sep 2016 09:00:00 +0000</pubDate>
---
>       <pubDate>Thu, 08 Sep 2016 18:00:00 +0900</pubDate>
```

Similarly for the translations; the originally provided time zone is used instead of UTC.

Corresponding line in `_layouts/news_feed.rss`:

```
<pubDate>{{ post.date | date: "%a, %d %b %Y %H:%M:%S %z" }}</pubDate>
```

Presumably `post.date` is handled differently now?
I should investigate what exactly changed.

**Comment by hsbt** [comment]
Confirmed! Thank you.

**Pull request merged**
