### PR TITLE
Add lang to html start tag

### PR DESCRIPTION
**Pull request by spk**
Fix warning:

`Warning: This document appears to be written in French. Consider adding lang="fr" (or variant) to the html start tag.`

### CODE REVIEW

**Comment by stomar** [comment]
I'm not sure about "zh_cn" and "zh_tw" as values for the lang attribute. Valid?

**Comment by hlcfan** [comment]
It should be "zh-CN" or "zh-TW".
Please get it from `lang_code` in `_config.yml`.

**Comment by spk** [comment]
Thanks its fixed

**Comment by stomar** [comment]
Thanks! No time for testing today, I'll look into it tomorrow.

**Comment by JuanitoFatas** [comment]
@spk This warning seems gone, please reopen if happens again, thank you!

**Pull request closed without merging**
