### PR TITLE
Translate 2014-10-27-ruby-1-9-3-p550-is-released (id)

### PR DESCRIPTION
**Pull request by meisyal**
Hello,

This is Bahasa Indonesia translation for Ruby 1.9.3-p550 is released (https://www.ruby-lang.org/en/news/2014/10/27/ruby-1-9-3-p550-is-released). Please, do review this PR @gozali !

Thank you.

### CODE REVIEW

**Comment by gozali** [comment]
:+1: thanks @meisyal

**Comment by stomar** [comment]
Please squash into a **single commit** (`Translate 2014-10-27-ruby-1-9-3-p550-is-released (id)`) and force push your topic branch.

**Comment by meisyal** [comment]
@stomar I have done. Please, review my last commit!
Thanks.

**Comment by stomar** [comment]
Thanks! Merged manually as 5ce92583049ccb32b1274b54b74dbda1bf6bd1b1. cc @gozali

**Pull request closed without merging**
