### PR TITLE
Update 2015-03-06-google-summer-of-code-2015.md (zh_cn)

### PR DESCRIPTION
**Pull request by 1ternal**
translate post's title(zh_cn)

Follow up of #1083

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
Can you [rebase and squash](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request) against master?

**Comment by 1ternal** [comment]
@JuanitoFatas please check it out :cry:

**Comment by JuanitoFatas** [comment]
Ah nice! But you haven't rebase with *latest master*.

1. Go to master branch: `git checkout master`
2. Pull latest changes from master to local: `git pull origin master` (suppose origin is `git@github.com:ruby/www.ruby-lang.org.git`, change accordingly)
3. `git checkout zh_cn/translate-google-summer-of-code-2015`
4. `git rebase master`
5. resolve conflicts
6. Update this pull request: `git push -f [your-forked-remote] zh_cn/translate-google-summer-of-code-2015`

Let me know if you encounter any problems.

**Comment by 1ternal** [comment]
I don't know I can rebase with **master**, just working on my forked repo. :fearful:

**Comment by 1ternal** [comment]
@JuanitoFatas  I made it. :lollipop: 
btw, I don't know I can rebase master, and I have no exp to collabarte with ppl using git.

**Comment by JuanitoFatas** [comment]
Excellent!

**Pull request merged**
