### PR TITLE
Translate all November 2014 news (id)

### PR DESCRIPTION
**Pull request by meisyal**
New pull request from the [old one](https://github.com/ruby/www.ruby-lang.org/pull/1116).
I have made the link of post reference to translated post when they exist. The title of translated link is translated too. But, if the translated link post doesn't exist I used the default language or English post as the reference without any title link translation.

Please, review this PR @gozali and @stomar!

Thank you so much.

### CODE REVIEW

**Comment by stomar** [comment]
Thanks! Seems ok formally; the content must be reviewed by @gozali.

**Comment by meisyal** [comment]
Thanks @stomar. I am waiting for review from @gozali.
I would like to push a new commit because some translated post links already existed (October 2014 post). Then, I will squash them into a single commit.

**Comment by meisyal** [comment]
Hello, @gozali. Please, review my work!
Thank you.

**Comment by gozali** [comment]
Looks good

+1

**Comment by stomar** [comment]
@meisyal, @gozali

Thanks for your work!
(And sorry for the delay, I'm rather busy these days.)

**Comment by meisyal** [comment]
Thank you so much @stomar. Enjoy your working!
No problem. I hope I can still contribute to this project.

**Pull request merged**
