### PR TITLE
Updated and translated community/ruby-core/* to German (de).

### PR DESCRIPTION
**Pull request by mgruner**
This is my first contribution here, please let me know if I got everything right.

I added a new file for the patch writer's guide, even though the English content seems slightly outdated (refers to SVN).

### CODE REVIEW

**Comment by mgruner** [comment]
@hsbt is there anything I can do to bring this one forward? I also created it to check how much activity/interest there is in contributions for the German translation, which is outdated.

**Comment by Quintus** [comment]
I think it is time to confess that I lack the time to further maintain the German translation. I don’t use Ruby much anymore, and have been moving onto a different field alltogether. Maybe @stomar can take a look.

**Comment by mgruner** [comment]
> I think it is time to confess that I lack the time to further maintain the German translation. I don’t use Ruby much anymore, and have been moving onto a different field alltogether. Maybe @stomar can take a look.

@Quintus thanks for the update. How can we move forward? I am interested in contributing regularly. Are there no German maintainers left who are able to review contributions? In that case, how to apply for a maintainer role?

**Comment by Quintus** [comment]
I think I am the last one from the German team left. I don’t think that I can add you as a maintainer; organisational changes need to go through @hsbt as far as I know.

On the changes themselves, they look fine to me. I would certainly welcome it if someone took over the translation efforts from me.

**Review by Quintus — APPROVED** [review]

**Pull request merged**
