### PR TITLE
Move Ruby 2.4 to EOL

### PR DESCRIPTION
**Pull request by eregon**
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-4-10-released/

cc @mame @unak

### CODE REVIEW

**Comment by eregon** [comment]
Could we merge this?
Should we move 2.5.8 to `security_maintenance`, or do that later?

**Comment by hsbt** [comment]
We will update them after publishing the official annoucement by @unak

**Comment by eregon** [comment]
I'm fine to close this if we're going with the more complete https://github.com/ruby/www.ruby-lang.org/pull/2412

**Comment by eregon** [comment]
I updated this, I think together with #2420 it's complete.

**Pull request merged**
