### PR TITLE
Paralleling Travis jobs to shorten build duration

### PR DESCRIPTION
**Pull request by alaxalves**
Fixed the in-between travis build caching problem and makes the jobs parallel making easier to identify an eventual issue.

### CODE REVIEW

**Comment by stomar** [comment]
Could you please shortly explain the „in-between travis build caching problem“?

**Comment by alaxalves** [comment]
> Could you please shortly explain the „in-between travis build caching problem“?

When you add caching like this:
``` yml
cache:
  bundler: true
```
to Travis you must specify a directory to cache as specified [here](https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies). This was causing Travis not cache properly sometimes. Since ruby-lang does not specify a different folder to install dependencies just using `cache: bundler` to the yml fixes it.

**Comment by stomar** [comment]
I added a commit with a simpler config: `matrix` is not necessary here (no global env vars), and using TASK instead of SCRIPT makes the log more readable, IMO.

What do you think?

**Comment by alaxalves** [comment]
@stomar I think it's great. Thank you for the feedback.

**Pull request merged**
