### PR TITLE
Translate 2014-10-27-ruby-2-0-0-p594-is-released (id)

### PR DESCRIPTION
**Pull request by meisyal**
Bahasa Indonesia translation for Ruby 2.0.0-p594 is released (https://www.ruby-lang.org/en/news/2014/10/27/ruby-2-0-0-p594-is-released/).
Please, review my translation @gozali!

Thanks.

### CODE REVIEW

**Comment by gozali** [comment]
+1 thanks @meisyal

**Comment by meisyal** [comment]
@gozali mistake. I have changed lang from "en" to "id".

**Comment by stomar** [comment]
Please
* link to translated posts when they exist
* squash into a **single commit** (`2014-10-27-ruby-2-0-0-p594-is-released (id)`) and force push

**Comment by meisyal** [comment]
Thank you for reviewing, @stomar.

May I ask a question?
If link to translated post doesn't exist, should I choose the default language as the reference link (English version)?

**Comment by stomar** [comment]
Yes. But e.g. `id/news/_posts/2014-10-27-changing-default-settings-of-ext-openssl.md` exists, so you should link to it (using the translated title).

**Comment by meisyal** [comment]
OK. I am currently working on it.

**Comment by meisyal** [comment]
@stomar I have done. Please, review my last commit!
Thanks.

**Comment by stomar** [comment]
Thanks! Merged manually as 719298f3610b905909bbd4f54f65e07a93b8d2e9. cc @gozali

**Pull request closed without merging**
