### PR TITLE
Add .ruby-version and upgrade Ruby to 2.2.4

### PR DESCRIPTION
**Pull request by JuanitoFatas**
This Pull Request adds back `.ruby-version` (Why this file being git-ignored?) and upgrade Ruby to 2.2.4.

### CODE REVIEW

**Comment by stomar** [comment]
Regarding upgrade to latest Ruby: take into account that binaries are not immediately available for Travis (and? Heroku).

Why should .ruby-version be included?

**Comment by yous** [comment]
By the way, 2.2.4 binaries are now available. I restarted builds.

**Comment by JuanitoFatas** [comment]
> Why should .ruby-version be included?

Personally, I rely on this file to switch ruby version in different projects. What do you think?

> By the way, 2.2.4 binaries are now available. I restarted builds.

Thank you!

**Comment by stomar** [comment]
The downside is having another file that needs to be updated.

Since I do not use it, I would rather have other opinions.

**Comment by hsbt** [comment]
I against to contain personal or specific tool configuration file to team repository.

**Comment by JuanitoFatas** [comment]
> I against to contain personal or specific tool configuration file to team repository.

Sorry should have said personal, I thought [.ruby-version is very common](https://gist.github.com/fnichol/1912050), closing this.

**Comment by hsbt** [comment]
@JuanitoFatas In my team, We added `.ruby-version` to gitignore and programmer create `.ruby-version` personally.

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas In my team, We added .ruby-version to gitignore and programmer create .ruby-version personally.

Sounds good! Thank you for the advice.

**Pull request closed without merging**
