### PR TITLE
Unmark zh_cn as unmaintained

### PR DESCRIPTION
**Pull request by JuanitoFatas**
zh_cn mostly has been updated, remove this unmaintained notice.

--

Related #1074

### CODE REVIEW

**Comment by hlcfan** [comment]
Thank you!

**Comment by JuanitoFatas** [comment]
@stomar @hsbt 👌 ?

**Comment by stomar** [comment]
How about zh_*/security?
And who is maintainer for zh_cn?

**Comment by hlcfan** [comment]
I'll have a look tomorrow.

**Comment by hlcfan** [comment]
@stomar I'll have a look tomorrow.

**Comment by stomar** [comment]
Sorry, I did not see the most recent commits, zh_cn/security _is_ updated.

**Comment by JuanitoFatas** [comment]
> Who are maintainers for zh_cn?

@hlcfan and @AndorChen.

**Comment by stomar** [comment]
Thanks!

@JuanitoFatas Go ahead :+1:

**Pull request merged**
