### PR TITLE
Translate Ruby 2.3.3 released post (id)

### PR DESCRIPTION
**Pull request by meisyal**
As titled. @gozali.

### CODE REVIEW

**Comment by gozali** [comment]
thank @meisyal, one comment though please add newline to end of file

**Comment by meisyal** [comment]
Fixed by adding a new line at the end of file.

**Comment by gozali** [comment]
Thank, all good +1

**Comment by stomar** [comment]
I think @gozali meant a single newline character; you added a surplus empty line.

**Comment by meisyal** [comment]
Thank you, @stomar.

**Pull request merged**
