### PR TITLE
Add ruby podcasts page (en)

### PR DESCRIPTION
**Pull request by jacobherrington**
I feel it would be a great idea to list some podcasts, check the commit messages for more context. 👍

### CODE REVIEW

**Comment by hsbt** [comment]
This is duplicate as https://github.com/ruby/www.ruby-lang.org/pull/1466

**Comment by jacobherrington** [comment]
@hsbt I would be happy to pick up those changes in this PR. What do you think?

**Comment by stomar** [comment]
I‘ll look into those two PR‘s.

**Comment by stomar** [comment]
I merged the older PR. Please feel free to suggest any improvements.

**Comment by jacobherrington** [comment]
@stomar I am closing this PR and addressing a couple of thoughts in #1999. Thanks!

**Pull request closed without merging**
