### PR TITLE
Translate 2014-10-27-ruby-2-1-4-released (id)

### PR DESCRIPTION
**Pull request by meisyal**
Please, review my translation @gozali.

Thank you.

### CODE REVIEW

**Comment by gozali** [comment]
+1

thanks @meisyal

**Comment by meisyal** [comment]
@gozali mistake. I have changed lang from "en" to "id".

**Comment by stomar** [comment]
Please
* check whether translations for linked posts exist
* squash into a single commit (`Translate 2014-10-27-ruby-2-1-4-released (id)`) and force push

**Comment by meisyal** [comment]
@stomar I have done. Please, review my last commit!
Thanks.

**Comment by stomar** [comment]
Thanks! Manually merged as 4762364e3bf8fcd0aa7ed8b695589bfe4fb4393f. cc @gozali

**Pull request closed without merging**
