### PR TITLE
Official FAQ

### PR DESCRIPTION
**Pull request by zzak**
Replaces #477 with an origin topic branch for open collaboration

### CODE REVIEW

**Comment by hsbt** [comment]
@zzak Any status? I'm ok to merge this contents to www.r-l.o.

**Comment by zzak** [comment]
@hsbt I think the formatting for chapters 7-11 is still unfinished

**Comment by zzak** [comment]
i.e.: https://github.com/ruby/www.ruby-lang.org/blob/official_faq/en/documentation/faq/11/index.md

**Comment by stomar** [comment]
IMO it needs some work before merging. I plan to have a look at it in the next weeks.

@zzak How is your opinion on these general suggestions:

* there should be a disclaimer that the content is currently in parts **very** outdated
* maybe credits to Shugo Maeda and reference to original source (namely ...?)
* structure: `faq/` page with only general information (see above) and table of contents, chapter 1 for consistency under under `faq/1/` like the other chapters

**Comment by stomar** [comment]
@zzak I really would like to base further work on the current environment, the branch uses a very old gemset I couldn't get running offhandedly (and I don't want to waste time on it); would you mind if I rebase the branch?

**Comment by zzak** [comment]
> would you mind if I rebase the branch?

Feel free! This branch is open to any contributor to pitch in.

> there should be a disclaimer that the content is currently in parts very outdated

+1, the top of each page should mention the state of this document

> maybe credits to Shugo Maeda and reference to original source

Sounds good, I first found it [here](http://ruby-doc.org/docs/ruby-doc-bundle/FAQ/FAQ.html), although this may not be the original source.

> structure: faq/ page with only general information (see above) and table of contents

I'm fine with restructure into pages, instead of folders. +1


Thanks for moving this forward!!

**Comment by stomar** [comment]
See also "The Ruby FAQ" from RubyGarden in the Internet Archive: https://web.archive.org/web/20080603033227/http://faq.rubygarden.org/, which was based on this FAQ and may include some improvements.

**Comment by stomar** [comment]
Note: The FAQ is linked to from `documentation/ruby-from-other-languages/`; the link should be updated when this is merged.

**Comment by stomar** [comment]
@hsbt @zzak 

I'm planning to merge very soon. What do you think?

There are still some out-dated parts, but for the time being I would keep them, due to lack of time or/and in-depth knowledge.

I might do some minor improvements before merging, but no major changes.

**Comment by zzak** [comment]
@stomar Thank you for all your work on this!

Since you have a good idea about what might be outdated and or missing, could you add some comments here about that?

It might also be interesting if we had some way to represent either WIP or needs help sections/pages in the UI that would link to the repository and how to contribute.

This can come later, but while it's still fresh in your head let's start a list here of pages that need more work.

**Comment by hsbt** [comment]
@zzak Thank you for your great work. I'm ok to merge this.

**Comment by stomar** [comment]
@zzak

> Since you have a good idea about what might be outdated and or missing, could you add some comments here about that?
>
> It might also be interesting if we had some way to represent either WIP or needs help sections/pages in the UI that would link to the repository and how to contribute.

All sections that IMO need updates are already marked; but additionally opening an issue here that keeps track of them is a good idea.
I could also modify `_includes/faq-notice.html`, which currently appears on every FAQ page, to include a link to the repository.

**Pull request merged**
