### PR TITLE
Update release list on downloads page (zh_cn)

### PR DESCRIPTION
**Pull request by hlcfan**
Update related to issue #1321.

**在做安全性维护的版本（很快 EOL！）**looks weird, how about **在做安全更新的版本**？
@JuanitoFatas Please give some comments.

### CODE REVIEW

**Comment by stomar** [comment]
@hlcfan Can I merge?

**Comment by AndorChen** [comment]
@hlcfan Looks fine to me. But IMHO, "EOL" should be translated.

**Comment by stomar** [comment]
Closed with 770eed84e7349537a901e2a95cacad725dc30ed2.

**Pull request closed without merging**
