### PR TITLE
Translate ConFoo Vancouver 2016 is looking for Ruby speakers (id)

### PR DESCRIPTION
**Pull request by meisyal**
I just translated "ConFoo Vancouver 2016 is looking for Ruby speakers" into Bahasa Indonesia.
Please, review my translation @gozali. Thank you.
cc: @stomar

### CODE REVIEW

**Comment by gozali** [comment]
Looks good

+1

**Comment by stomar** [comment]
Thanks. Note that commit messages should be 50 characters or less.

**Comment by meisyal** [comment]
Thank you for merging this @stomar.
I am sorry. If I have another pull request, I will wrap the commit message.

**Comment by stomar** [comment]
A common rule is 50/72 formatting (50 for the subject line, 72 for the message body), see e.g. http://chris.beams.io/posts/git-commit/.

**Comment by meisyal** [comment]
Thank you (y) for giving the reference :+1: 
To be honest, I don't read the contributing guidelines properly.

**Pull request merged**
