### PR TITLE
Translate ConFoo Montreal 2017 post (pt)

### PR DESCRIPTION
**Pull request by jcserracampos**

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
cc @alanwillms & @fpgentil

**Comment by alanwillms** [comment]
Looks good

**Comment by stomar** [comment]
@JuanitoFatas Re squash commits: I think it's not necessary to clobber the history by listing squashed commits that only fix typos in the commit message.

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas Re squash commits: I think it's not necessary to clobber the history by listing squashed commits that only fix typos in the commit message.

Noted, will remove those next time, thanks!

**Pull request merged**
