### PR TITLE
Use Jekyll 4

### PR DESCRIPTION
**Pull request by hsbt**
Jekyll 4 was improved the generation time for markdown.

### CODE REVIEW

**Comment by mame** [comment]
@znz said that updating rouge requires updating css.  Need to confirm if it is rendered correctly.

**Comment by jcserracampos** [comment]
@mame I was thinking... Can we make a preview pipeline to new PRs?
Something like netlify does.

**Comment by hsbt** [comment]
We can use heroku preview app for this.

**Comment by jcserracampos** [comment]
@hsbt It'd incredible because we can catch more errors when seeing live pages.

**Comment by jcserracampos** [comment]
I found no problems with render.
LGTM.

**Comment by hsbt** [comment]
@jcserracampos Thanks!

**Pull request merged**
