### PR TITLE
Translate Ruby 2.4.0-preview3 released post (id)

### PR DESCRIPTION
**Pull request by meisyal**
As titled. Please, review this translation @gozali.

### CODE REVIEW

**Comment by meisyal** [comment]
One more @gozali :)

**Comment by stomar** [comment]
note broken SHA512 sums, c8367357debc2b2f98a18c16bd8dee9534b5a8af.

**Comment by meisyal** [comment]
Done. I just fixed it.

**Comment by meisyal** [comment]
Done. I just fixed it.

**Comment by gozali** [comment]
LGTM +1

**Pull request merged**
