### PR TITLE
Adding Works on Arm logo on our English website.

### PR DESCRIPTION
**Pull request by junaruga**
This PR is to add Arm's logo sponsoring us for a Ubuntu Arm neoverse server (RubyCI - "Ubuntu arm neoverse") as their project Works on Arm to our English website: https://www.ruby-lang.org/en/about/website/ as our appreciation.

I got the logo image from "Arm Blue Logo" on [this page](https://www.arm.com/company/policies/trademarks/guidelines-corporate-logo). The url is https://www.arm.com/-/media/global/logos/Arm-logo-blue-pms313.svg . The image file is originally .svg file. I converted it to png file (image size 237 x 72 pixels).

You can check the updated document [here](https://github.com/junaruga/www.ruby-lang.org/blob/wip/website-sponsor-arm/en/about/website/index.md) on my forked repository.

I am going to confirm our folks at Arm before merging this PR.

### CODE REVIEW

**Comment by junaruga** [comment]
I would ask you for the PR's review after I can contact with people at Arm.

**Review by sorah — APPROVED** [review]
Changes look good so approving, but acknowledge to hold merging until Arm team's confirmation

**Comment by junaruga** [comment]
A person at Arm told me that they would prefer to use [Works on Arm](https://www.arm.com/markets/computing-infrastructure/works-on-arm)'s logo rather than Arm's logo. And I am asking them to get the Works on Arm's logo image file now.

**Comment by junaruga** [comment]
> A person at Arm told me that they would prefer to use [Works on Arm](https://www.arm.com/markets/computing-infrastructure/works-on-arm)'s logo rather than Arm's logo. And I am asking them to get the Works on Arm's logo image file now.

I received a Works on Arm logo image file (png file) from a person at Arm. The file was the width x height = 7808px x 650px (file size: 751.3 KB) with a transparent background color. As the image size was bigger than other images under the `images/sponsor/*.png` files, I scaled the image size down by myself into the 300px x 26px (file size: 9.5 KB).

The reason why I decided the width 300px is because the image file with longest width is `mackerel.png` whose width is 300px. Though the `mackerel.png` has padding spaces unilke the `works-on-arm.png`, the appearance is a bit different.

You can check the updated document [here](https://github.com/junaruga/www.ruby-lang.org/blob/wip/website-sponsor-arm-debug/en/about/website/index.md) on my forked repository again.

**Review by hsbt — APPROVED** [review]

**Comment by hsbt** [comment]
@junaruga Thank you ❤️

**Pull request merged**
