### PR TITLE
Russian version of rubyinstaller website

### PR DESCRIPTION
**Pull request by aristofun**
Please update the link to match the language of `ru/installation/` page as well

### CODE REVIEW

**Comment by stomar** [comment]
The .ru site doesn‘t seem to be related in any official way to rubyinstaller.org, so we should _not_ link to it.

**Comment by aristofun** [comment]
What would make it more (or less) "official" than rubyinstaller.org?

**Comment by aristofun** [comment]
It is "officially" and publicly forked & available on github (what is officially encouraged by .org authors)
and seems like professionally translated: https://github.com/installero/rubyinstaller.ru

Please reconsider

**Comment by stomar** [comment]
That doesn‘t mean anything, anybody can create his own fork.

We at ruby-lang.org can not guarantee that the provided binaries are unmodified and will be so also in the future, so we should still link to the original site.

**Pull request closed without merging**
