### PR TITLE
Remove Google Analytics

### PR DESCRIPTION
**Pull request by stomar**
Remove the Google Analytics tracking code from the site.

### CODE REVIEW

**Comment by stomar** [comment]
I do not see any benefits from using it, only concerns.

Waiting for reviews/opinions.

**Review by JuanitoFatas — APPROVED** [review]
I’m in favor of removal 👍🏼

**Comment by Nakilon** [comment]
> I do not see any benefits from using it, only concerns.

I suppose it shows problems and traffic sources. If you don't want it to track you, you can install U-Block Origin.

**Comment by stomar** [comment]
> If you don't want it to track you, you can install U-Block Origin.

I did not mean concerns as a visitor, but rather as a site owner; some points are made for example [here](https://dev.to/markosaric/why-you-should-remove-google-analytics-from-your-site-5c7h).

**Comment by hsbt** [comment]
I'm considering to this now. Because GA provides statistics of new users of ruby lang to me.

**Comment by hsbt** [comment]
OK, I decided to remove it from www.ruby-lang.org.

**Pull request merged**
