### PR TITLE
Translate the news ruby 2.0.0-p645 released(zh_cn)

### PR DESCRIPTION
**Pull request by aidewoode**
screen shot 2015-05-27 at 8 57 05 pm

Related [#1074](https://github.com/ruby/www.ruby-lang.org/issues/1074)

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
@pmq20 @hlcfan @liuzxc @tzwm @happybai @diguage @alex-marmot @itsliupeng
@cassiuschen @1ternal @killernova @VincentZhao @reyesyang @jun1st @springwq
@Huibean @junzh0u @zigzagpig @42thcoder @GaaraLi @shouxian @johnnyhappy365
@aidewoode @Yunfei1982

Please review :bow:

**Comment by aidewoode** [comment]
@JuanitoFatas I think this news 's translation is all right , it can be merged

**Comment by aidewoode** [comment]
@JuanitoFatas  Hi , my translation for this news is completed ,and it can be merger. And I think maybe you don't notice my last comment,  So I write this comment for you.

**Comment by aidewoode** [comment]
@springwq Thanks comment , I will update later.

**Comment by aidewoode** [comment]
@JuanitoFatas If don't have any other issue, I think this news can be merged.

**Comment by JuanitoFatas** [comment]
Thanks! Merged as e4829fa. Thanks @springwq for reviews! :heart:

**Pull request closed without merging**
