### PR TITLE
Add some contents to ja and en installation pages.

### PR DESCRIPTION
**Pull request by igaiga**
### ja/documentation/installation
Add follows

- Windows
  - ActiveScriptRuby (refer to download page)
  - RailsInstaller (refer to download page)
- Web Service
  - Nitrous.io

### en/documentation/installation
Add follows

- Windows
  - ActiveScriptRuby
- Web Service
  - Nitrous.io

### CODE REVIEW

**Comment by takaokouji** [comment]
:+1:

**Comment by stomar** [comment]
I'm not sure about the web service; it's the *installation* page.

And the `en` content needs a language review; I could do that later.

**Comment by hsbt** [comment]
I agree with @stomar 's opinion. Netrous.io should not be put "installation" page.

**Comment by igaiga** [comment]
> I'm not sure about the web service; it's the installation page.

I got it. I'm looking for better page.

> And the en content needs a language review; I could do that later.

Thanks! :sparkles:

**Comment by igaiga** [comment]
@stomar @hsbt 
I've made a "developing on browser" page and move Nitorous.io descriptions.
Could you review again?

**Comment by igaiga** [comment]
@stomar  How about this?

**Comment by stomar** [comment]
This PR does too many different things, I'm not inclined to merge.

- RailsInstaller (ja): submitted as a separate PR this could be merged easily, it's only a translation of existing content
- ActiveScriptRuby: I cannot judge about that since I don't know what it is (there doesn't seem to be any English information); is it an installer? is it a modified Ruby? who provides it?
- Nitrous.io: I'm rather against promoting a paid service.

@hsbt, @chikamichi, @makimoto, ..., what do you think?

**Comment by hsbt** [comment]
@stomar @igaiga 

>ActiveScriptRuby: I cannot judge about that since I don't know what it is (there doesn't seem to be any English information); is it an installer? is it a modified Ruby? who provides it?

ActiveScriptRuby(ASR) is maintained by arton who is Ruby committer. If this installer page has only japanese infomation, we should not put this section into english installation page.

>Nitrous.io: I'm rather against promoting a paid service.

It's important thing. I agree with you.

**Comment by igaiga** [comment]
@stomar @hsbt 
Thanks to comment. :)

- RailsInstaller (ja)
 I'll throw new PR cutting the section from this PR.

- ActiveScriptRuby(ASR)
I'm waiting the conversation.

- Nitrous.io
I thought the information is useful for beginners because it's one of easiest way to start development Rails (and Ruby). I've heard many "That's difficult to make dev env for Rails." comments.
But I also understood your opinion. It can be used at no charge, but it's a paid service.

**Comment by sorah** [comment]
- ASR seems providing information in Japanese only from me. +1 to introduce only in Japanese.
- -1 for mentioning paid service too. Even if it can be used without any charge, it's commercial service.

**Comment by igaiga** [comment]
I've split pull requests. So this PR is closed.

**Pull request closed without merging**
