### PR TITLE
Add cache.ruby-china.org download mirror

### PR DESCRIPTION
**Pull request by huacnlee**
Manage by [Ruby China](https://ruby-china.org/)

This mirror built on 150 CDN nodes in China via upyun.com, no sync, realtime update.

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
👍 

/fyi @dwradcliffe

**Comment by JuanitoFatas** [comment]
🎉 🎊

**Comment by dwradcliffe** [comment]
I'm curious how the mirrors are updated?

**Comment by huacnlee** [comment]
Use CDN feature, caching *.tar.*, *.zip 1 year.

David Radcliffe <notifications@github.com>于2016年4月18日 周一19:11写道：

**Comment by stomar** [comment]
@JuanitoFatas

I think adding a mirror to the official list needs thumbs up of @hsbt.

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas
> 
> I think adding a mirror to the official list needs thumbs up of @hsbt.

Oh noted it, sorry about that.

**Comment by JuanitoFatas** [comment]
@hsbt Do I revert this change?

**Comment by hsbt** [comment]
Don't need. I confirmed to latest binaries on 2 mirrors.

**Comment by stomar** [comment]
Good. I only wasn't sure whether the integrity of the listed mirrors are / should be / must be verified by ruby core.

**Pull request closed without merging**
