### PR TITLE
Fixed typo in to-ruby-from-php

### PR DESCRIPTION
**Pull request by mishin**

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
Hi @mishin! Could you edit title of your pull requests to be more specific (click edit button to edit it):

screenshot 2015-04-29 23 44 51

So that people could know each pull request's purpose.

Also could you please update the commit message to be more specific. To edit your commit message.

You can open Terminal, clone your forked branch:

```
git clone git@github.com:mishin/www.ruby-lang.org.git
```

Checkout to this pull request's branch (patch-10, see below picture):

screenshot 2015-04-29 23 42 21

```
git checkout patch-10
```

Edit your commit message:

```
git commit --amend
```

Now edit your commit message to something like:

```
Fix a translation of to ruby from php (ru)
```

Save. Then override this pull request's change:

```
git push -f origin patch-10
```

Then the commit message will be updated.

If any problem, please tell me. Thanks!

**Comment by mishin** [comment]
Hi JuanitoFatas. Thanks for such understandable tutorial for git!

**Comment by mishin** [comment]
I have a question with latest commit https://github.com/ruby/www.ruby-lang.org/pull/1057/commits
How I can correct it?

**Comment by JuanitoFatas** [comment]
To correct multiple commit's messages, you need to do a rebase. You can switch to master branch and use:

```
git rebase -i HEAD~8
```

Then editor will shows up with something like:

```
pick 9ab3337d Update index.md
pick 5ebdee94 Update index.md
...


# Rebase b1655e2..f09125c onto b1655e2
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

you can replace `pick` with `reword`:

```
reword 9ab3337d Update index.md
pick 5ebdee94 Update index.md
...


# Rebase b1655e2..f09125c onto b1655e2
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

When you save this file, it is going to open up editor for all commit you mark reword to let you change the commit message.

**Comment by gazay** [comment]
Thank you @mishin for fixes! And thank you @JuanitoFatas for help!

**Comment by mishin** [comment]
done, I squash all commits in one!

**Pull request merged**
