### PR TITLE
translate 2014-12-25-ruby-2-2-0-released(zh_cn)

### PR DESCRIPTION
**Pull request by Airmacho**
screen shot 2015-05-30 at 15 43 51
Related #1074

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
@pmq20 @hlcfan @liuzxc @tzwm @happybai @diguage @alex-marmot @itsliupeng
@cassiuschen @1ternal @killernova @VincentZhao @reyesyang @jun1st @springwq
@Huibean @junzh0u @zigzagpig @42thcoder @GaaraLi @shouxian @johnnyhappy365
@aidewoode @Yunfei1982 @Airmacho @cursorzz @isjia @debbbbie @AndyHelix

Please take a look. :smiley:

**Comment by aidewoode** [comment]
Need Space between Chinese character and English character, it will be more distinct.

**Comment by reyesyang** [comment]
Maybe we also need space between English Link and Chinese character. Such as `参考[Rails 4.2官方发布](http://weblog.rubyonrails.org/2014/12/19/Rails-4-2-final/)` should be `参考 [Rails 4.2官方发布](http://weblog.rubyonrails.org/2014/12/19/Rails-4-2-final/)`

**Comment by stomar** [comment]
Please squash into a **single commit** and force push your topic branch.

**Comment by JuanitoFatas** [comment]
Thanks for review @stomar, @reyesyang, @aidewoode. Thanks for your contribution @Airmacho. I've fixed many minor issues, please see e29c0f7.

**Pull request closed without merging**
