### PR TITLE
Partial #948 — Update downloads page for 2.2.0 (PT)

### PR DESCRIPTION
**Pull request by kkirsche**
Partial #948 — Update downloads page for 2.2.0 (PT)

### CODE REVIEW

**Comment by kkirsche** [comment]
Wanted to follow up on this

**Comment by hsbt** [comment]
I will merge this. ref. https://github.com/ruby/www.ruby-lang.org/pull/1055

**Comment by hsbt** [comment]
@kkirsche Thanks for your contribution!

**Comment by kkirsche** [comment]
Than you :smiley:

**Comment by stomar** [comment]
@kkirsche, cc @hsbt

Please note that the markup is massively broken, leading to wrong layout and broken links.
I'll fix.

**Comment by stomar** [comment]
Fixed with 0b189d93420c446f4ed641697adadf357a426a19.

**Pull request merged**
