### PR TITLE
Translate 2016-05-16-confoo-cfp (pt)

### PR DESCRIPTION
**Pull request by jcserracampos**

### CODE REVIEW

**Comment by stomar** [comment]
Thanks!

The commit message is misleading, should rather be `Translate 2016-05-16-confoo-cfp (pt)`; also the post title is not translated.

Please amend the commit.

**Comment by jcserracampos** [comment]
Sorry!
First time translating here.

I made changes and committed again.
Should I create a new pull request?

**Comment by stomar** [comment]
No, simply squash the commits (dropping the original commit message), and force push you branch again.

**Comment by JuanitoFatas** [comment]
> No, simply squash the commits (dropping the original commit message), and force push you branch again.

GitHub now has a squash and merge feature, we can use this?

screenshot 2016-06-07 13 34 23

**Comment by stomar** [comment]
Thank you for the translation!

Merged manually, I squashed and also removed an untranslated (English) paragraph.
Note that PR title and commit message are two different things.

@JuanitoFatas I'll need to look into that new feature some time soon.

**Pull request closed without merging**
