### PR TITLE
Update the most recent release of Ruby for Debian and Ubuntu

### PR DESCRIPTION
**Pull request by meisyal**
As mentioned on #1611, the most recent release of Ruby for Debian and Ubuntu is 2.3.1. These changes include other languages. I saw outdated installation page on some languages (`de`, `it`, `ja`, `pl`, and `zh_tw`). Beside that, there is **no installation page** for `tr` language. What do you think?
@stomar

### CODE REVIEW

**Comment by hsbt** [comment]
Thanks.

We should give up to update outdated locales.

**Comment by meisyal** [comment]
You're welcome.
OK. I hope the contributors for those languages are aware.

**Comment by znz** [comment]
How about using variables like downloads page?

**Comment by meisyal** [comment]
Ah, it's a good idea @znz. Using that method, we don't need to update each page when new version of Ruby is available. Should I work on it?

**Comment by znz** [comment]
@meisyal Yes, please.

**Comment by meisyal** [comment]
OK. Where should I put variables that contain Ruby version?
There are some `.yml` files.

**Comment by stomar** [comment]
Not sure whether it's worth while to keep the version information for specific distributions, or whether we should simply drop them.

(Regarding `tr`: it's unmaintained for a long time.)

**Comment by znz** [comment]
Debian stretch (stable)'s [ruby](https://packages.debian.org/search?keywords=ruby) is 2.3.3.
And Ubuntu 16.04.3 LTS's ruby is 2.3.1.

```
% lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
% /usr/bin/ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```

So it may be better to split versions to Debian and Ubuntu. Or it may be better to remove mention to version like yum and others.

**Comment by stomar** [comment]
Let's drop them. When we start splitting information for Debian and Ubuntu we should as well start to list Ruby versions for the various distribution versions, like Ubuntu 17.10, 17.04, ..., Debian Jessie, ... It would need incessant maintenance.

**Pull request merged**
