### PR TITLE
Add RubyConf Taiwan 2015 Ticket information news for zh_TW and en

### PR DESCRIPTION
**Pull request by ryudoawaru**
Add RubyConf Taiwan 2015 Ticket information news. Please review thanks!

### CODE REVIEW

**Comment by yous** [comment]
I think you should rename your files to `2015-08-04-rubyconf-taiwan-registration-is-open.md`, not `2015-8-4`.

**Comment by ryudoawaru** [comment]
Renamed, thanks

**Comment by ryudoawaru** [comment]
@hsbt  could you help me merging this PR?

**Comment by ryudoawaru** [comment]
@hsbt  :bow: :bow:

**Pull request merged**
