### PR TITLE
Translate all December 2014 news (id)

### PR DESCRIPTION
**Pull request by meisyal**
Hello, all.

I just translated all December 2014 news into Bahasa Indonesia. Please, review my work.
If there is a mistake or something, please feel free to tell me what it is. Thank you.

cc: @gozali @stomar

### CODE REVIEW

**Comment by gozali** [comment]
nice,

+1

thanks @meisyal

**Comment by hsbt** [comment]
:+1:

**Comment by meisyal** [comment]
Thank you for merging.

**Comment by stomar** [comment]
Thanks!

But please do not use CR/LF newlines, which causes problems with the news post excerpts displayed on the main page and archive pages.

**Comment by meisyal** [comment]
I saw LF newline on status bar of my editor when I was working this.
Did I do right thing? If not, what the newline should I choose?

**Pull request merged**
