### PR TITLE
Add WSL in documentation/installation (ja)

### PR DESCRIPTION
**Pull request by igaiga**
- Write descriptions for WSL(Windows Subsystem for Linux)
- It's one of good way to use native extention gems on Windows.

### CODE REVIEW

**Comment by stomar** [comment]
`en` is considered the main version of the site, so changes should be suggested and discussed for `en` first.

**Comment by igaiga** [comment]
英語版が #2009 でマージされたので、少しだけ手直しします。（英語版と日本語版で構成が違うけど英語版から少しフィードバックできそうなので）

**Comment by igaiga** [comment]
@sho-h @znz 
Could you review the PR? 
English page: #2009
The page structure is different from en page, so adopting ja page style.

**Comment by znz** [comment]
@igaiga 
#2009 added Windows WSL Ubuntu under Package Management Systems, but this PR added WSL under Windows.
I think same structure is easy to maintenance.

 [Windows Subsystem for Linux Installation Guide for Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10) is English page.
I think link to Japanese page is better if exists.

**Comment by sho-h** [comment]
@igaiga I have no additional opinion with @znz san's comment. 👍

**Comment by igaiga** [comment]
@znz OK, I'll move the contents to Package Management Systems. And English page and Japanese page has different structures. Top category of Japanese page is platform(like Windows), but English page has no category of platform. So I think it's good adding WSL into the platform category.

**Comment by igaiga** [comment]
And there is no ja page in docs.icrosoft.com
https://docs.microsoft.com/ja-jp/windows/wsl/install-win10
link redirect to en page.

**Comment by igaiga** [comment]
@JuanitoFatas Could you check this?

**Comment by JuanitoFatas** [comment]
Thanks igaiga-san and everyone who reviewed <3

**Pull request merged**
